### ISSUE TITLE
First paragraph of "purpose" is too detailed

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#1]
Goksel: I find this paragraph too detailed. Up to the sentence starting with "When designing" is ok. If we really want to give an example, just a TF would be enough without mentioning about microRNAs or antagonists, and keeping it short.

[import from LaTeX comment]

**Comment by jakebeal** [comment]
Handled this, but it needs another person to sanity check.

**Comment by cjmyers** [comment]
Looks good to me.
