### ISSUE TITLE
Better recommended role for Transcription Factor

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#11]
Replace the recommended URI for Transcription Factor role with something more appropriate (currently is URI for the term ``transcription activity.''

[imported from LaTeX]

**Comment by drdozer** [comment]
There are lots of relevant terms in GO. For example:

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0003700

"sequence-specific DNA binding transcription factor activity"

So this would be a suitable role to annotate a protein ComponentDefinition with to flag that it is a transcription factor. There's the related question of what terms to use in an interaction were a TF binds a region of DNA to modify transcription, but I haven't found terms for these yet.

**Comment by nroehner** [comment]
GO:0003700 or "sequence-specific DNA binding transcription factor activity" is what I had initially used, not just "transcription activity" as the issue suggests, but some thought an activity wasn't what we really wanted ("transcription factor").

**Comment by nroehner** [comment]
I'd be happy with GO:0003700, since it appears to be standard practice in GO to mark up proteins with the activities that they produce.

**Comment by nroehner** [comment]
As a stopgap, Goksel has suggested using a custom "hasFunction" annotation with http://identifiers.org/go/GO:0003700 as its value.

**Comment by goksel** [comment]
The role property in SBOL is used to refer to a type of biological molecule. However, the GO term suggested refer to a molecular function term. If there is a term for "Transcription Factor" rather than "Transcription factor activity", it would be more suitable.

**Comment by goksel** [comment]
How about "SBO:0000459 - stimulator" for activator TFs and "SBO:0000020 - inhibitor"  for repressor TFs?

**Comment by jakebeal** [comment]
Will be addressed by #7

**Comment by lenov** [comment]
If SBO terms are still needed, we can add children of stimulator and inhibitor for the activity, but also create a term in the functional entity branch, sibbling of channel, enzyme, receptor etc.

**Comment by cjmyers** [comment]
@goksel what shall we do about this one?  Have you added anything to the text for this yet?
