### ISSUE TITLE
Demote sbol-13006 to best practice.

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#119]
This rule states that a VariableComponent must have Variants, VariantCollections, or VariantDerivations. This one is tricky since we like to not create invalid things, so ideally we would force people to send a variant (i.e., a CD), a Collection, or a Derivation to the create method. This is a bit awkward though. Would be nice if this were demoted to a best practice.

**Comment by jakebeal** [comment]
I believe we've done similar weakenings to allow 0 cardinality in a number of other places, in order to allow "haven't filled this blank in yet" to be a valid state.  I think that it is valid here as well --- and in general, a variable with zero values is entirely valid, just not useful.
