### ISSUE TITLE
specification document missing figure update

### ISSUE THREAD

**Issue by Fontanapink** [SynBioDex/SBOL-specification#124]
In 2.2 specification document, in page 20, the figure 5 only shows 6 top-level classes.

**Comment by cjmyers** [comment]
Figure 5, should also have an "attachments" field 0..* that points to an Attachment object via a hollow-diamond arrow link.

After the figure and before the Serialization section, we need the following subsection:

The attachments property 

The attachments property is OPTIONAL and MAY specify a set of Attachment objects that are referenced by the TopLevel object. The Attachment class is described in more detail in Section~\ref{sec:Attachment}.

**Comment by tramyn** [comment]
@cjmyers: Could you check out this branch (https://github.com/SynBioDex/SBOL-specification/tree/issue124) and verify the changes before I have another editor merge my branch to the master branch?

**Comment by tramyn** [comment]
@cjmyers : a new fixed was made and the changes have been committed [here](https://github.com/SynBioDex/SBOL-specification/blob/issue124/uml/toplevel.pdf) for you to look at the new UML figure. Can you check before I attempt to merge to master branch.

**Comment by cjmyers** [comment]
Looks great. Thanks
