### ISSUE TITLE
Missing citations and citation links, s6p13

### ISSUE THREAD

**Issue by mikebissell** [SynBioDex/SBOL-specification#125]
Section 6, lines 34, 40, etc.

In section 6 overview several projects are mentioned, including IPTG, X-gal, SBML, CellML and Matlab, but they appear without links, and no references are provided.

**Comment by jamesscottbrown** [comment]
CellML and MATLAB had no references, as they were initially cited when first mentioned (in ``overview.tex``, but this paragraph was commented out). I've added references for these and SBML.

I haven't added references for IPTG and Z-gal: these are small molecule inducers rather than software projects.

**Comment by tramyn** [comment]
The following set of citations should be updated on the sbol.bib file. Current citations stored on there are incorrect. 

CellML: 
@article{cuellar2003overview,
  title={An overview of CellML 1.1, a biological model description language},
  author={Cuellar, Autumn A and Lloyd, Catherine M and Nielsen, Poul F and Bullivant, David P and Nickerson, David P and Hunter, Peter J},
  journal={Simulation},
  volume={79},
  number={12},
  pages={740--747},
  year={2003},
  publisher={Sage Publications}
}

SBML: 
@article{hucka2003systems,
  title={The systems biology markup language (SBML): a medium for representation and exchange of biochemical network models},
  author={Hucka, Michael and Finney, Andrew and Sauro, Herbert M and Bolouri, Hamid and Doyle, John C and Kitano, Hiroaki and Arkin, Adam P and Bornstein, Benjamin J and Bray, Dennis and Cornish-Bowden, Athel and others},
  journal={Bioinformatics},
  volume={19},
  number={4},
  pages={524--531},
  year={2003},
  publisher={Oxford University Press}
}
