### ISSUE TITLE
Clarification: where did Figure 29's displayIds come from?

### ISSUE THREAD

**Issue by mikebissell** [SynBioDex/SBOL-specification#129]
I don't feel very strongly about this, but you might wish to clarify the origin of displayIds like "BBa_R0010" in figure 29. Searching the full pdf reveals the origin of that one to be the iGEM parts registry, but in context it's a little unclear what's going on. 

Also, it's not obvious why displayId is included in Figure 29, but persistentIdentity is not. Seems to me persistentIdentify is more important. I understand there is a shorthand at work, but newcomers won't get it.

As a courtesy, let's strive to make our examples locally comprehensible to developers who aren't reading the whole spec in one go.

**Comment by cjmyers** [comment]
No longer relevant to SBOL 3
