### ISSUE TITLE
'wasDerivedFroms' is linguistically awkward.

### ISSUE THREAD

**Issue by mikebissell** [SynBioDex/SBOL-specification#135]
`-wasDerivedFroms[0..*] : URI`

I realize this ship has sailed for 2.2.1, but perhaps for v3 we might devise a less awkward field label for an entity's list of multiple sources?

The label 'wasDerivedFroms' makes sense in context, but to a newcomer, it might appear to be inhumane gibberish. <grin/>

Suggestion: choose a plural noun.

Same could be said of 'wasGeneratedBys'.

**Comment by udp** [comment]
Please.

**Comment by udp** [comment]
Fixed in SBOL3
