### ISSUE TITLE
Uniform (and accessible) color style for UML diagrams

### ISSUE THREAD

**Issue by mikebissell** [SynBioDex/SBOL-specification#139]
See also the related ticket about Figure 34 (#138). This ticket (#139) is much broader:

In UML class diagrams, color really helps distinguish foreground from background -- for readers who can perceive it.

But color must be applied uniformly throughout the spec. Please standardize the application of color throughout this document.

Additionally, when color appears, it is a CAD symbol, and every meaningful symbol require's a definition that's easy to locate. On each figure, link to a **key** explaining the meaning of each color. (Tangentially, I recommend also including, in the same location, a visual key to the UML line art symbols.)

Please also remain sensitive to readers with vision irregularities, including _unusual color perception_ and _low visual contrast_. For example, if you're going to use black foreground text, you might choose fairly pale, low-saturation background colors. This will also help when we try to display the figures on a printer or a projector, only to discover that our device's color calibration is way off. High-contrast figures will fail gracefully, cutting through a bad projector profile, whereas low-contrast figures may be reduced to illegible blocks of ink.

**Comment by palchicz** [comment]
The UML diagram under "Mapping Between SBOL 1.1 and SBOL 2.x" is the only remaining UML diagram with color.  I think we can close this issue if we convert it to black & white, which will be consistent with the rest of the document.

**Comment by palchicz** [comment]
Actually, on closer inspection, the colors in the diagram under "Mapping Between SBOL 1.1 and SBOL 2.x" have meaning which are described in the caption.  Making the changes to the diagram under "Codon Optimization" will be sufficient to close this issue.
