### ISSUE TITLE
Serialization example runs off right margin

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#15]
Mike B: ``DNA sequences run off the page.
Historically, this has often been a problem with long DNA string datatypes that don't permit inline whitespace. They're impossible to print or justify for web presentation without breaking the validity of the document.''

Goksel: I like the Genbank files having 60 nucleotides in one row. :) I keep Mike's comment here in case if someone else has any suggestion.

[imported from LaTeX]

**Comment by goksel** [comment]
I added linespacing for the long sequences and examples look ok now. Does anyone have other suggestions?
