### ISSUE TITLE
Have enough people looked at this history?

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#16]
The text in the History section needs thorough review by the community.  We are certain that there are many errors, including missing people.  Please send input to fix these errors.
People who are known to have reviewed so far: Chris Myers, Jake Beal.

**Comment by jakebeal** [comment]
Need to make sure that at least every current and former editor plus Herbert is OK with what is said.

**Comment by cjmyers** [comment]
Confirm all participants in any meeting get a mention.  Also, substantial participants on the list who have not attended a meeting should get a mention.

**Comment by jakebeal** [comment]
Finished per 2.0; transferring to 2.0.1

**Comment by jakebeal** [comment]
Everybody has had more than enough time to ruminate upon this.
