### ISSUE TITLE
Duplicated section ("Adding Provenance" -> "Usage")

### ISSUE THREAD

**Issue by jamesscottbrown** [SynBioDex/SBOL-specification#165]
Subsections 12.9.2 and 12.9.4 are duplicates of the "Usage" subsection of "Adding Provenance".

One of these should clearly be deleted, but I'm not sure which.

**Comment by tramyn** [comment]
Note: 
- The merge was caused from this branch: https://github.com/SynBioDex/SBOL-specification/pull/146
- The issue that created this branch was reported here: https://github.com/SynBioDex/SBOL-specification/issues/108

**Comment by tramyn** [comment]
changes reflected in commit: https://github.com/SynBioDex/SBOL-specification/commit/7f15b784b35215c0e3603bdbe8c85f196a73e429
