### ISSUE TITLE
Confirm that BioPax terms in data model example match model specification

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#18]
ComponentDefinition.types in the following figure are not consistent with the list of BioPax ontological terms described previously in the Data Model section. 

Nic: Should now be consistent.  Need a second person to confirm.

[imported from LaTeX]

**Comment by goksel** [comment]
Is there any chance to find out which figure?

I briefly checked a few places and everything seems ok.

**Comment by bbartley** [comment]
I originally raised this issue in a very early draft of the spec document.  Nic corrected the problematic figures as requested.  This issue can be closed now.
