### ISSUE TITLE
Separate weak required rules into two validation rules

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#180]
Consider the following weak required SBOL validation error:

sbol-10513: Each URI contained by the sequences property of a ComponentDefinition MUST refer to a Sequence object.

The reason this is a weak requirement is that it cannot always be checked, since the URI may not always be able to be dereferenced to an object.  In other words, the SBOLDocument being validated may be incomplete, and the referenced object may not be contained within the document being validated.  However, if the URI does dereference then the object found MUST be a Sequence object.

The SBOL Validator has two ways to validate this rule.  A strict way in which the inability to dereference the object is an error (i.e., the incompleteness of the document is reported) or a weak way in which the error is only thrown when the object can be dereferenced and it is not a Sequence object.  In other words, the “Allow incomplete documents” option can toggle this requirement between a weak and a strong requirement. 

The plan was to group the errors/warnings by type and simply report the number of each type of error with a link to get the more detailed messages.  There would also be text to tell the user that they could change the flags to potentially eliminate the reporting of these errors. 

We should split the validation error above (and similar ones) into two errors: 

sbol-10513: Each URI contained by the sequences property of a ComponentDefinition MUST refer to a Sequence object. (weak required)

sbol-10XXX: Each URI contained by the sequences property of a ComponentDefinition SHOULD be able to be dereferenced. (best practice)

**Comment by ysistarter** [comment]
@cjmyers should code in SBOL-Validator be updated as well, or is the scope of this issue limited to the spec?

**Comment by cjmyers** [comment]
Yes, this one is pretty involved.  It would entail creating a lot of new validation rules.  Essentially you need one for each weak required one.  Also the library needs to be updated.

**Comment by jakebeal** [comment]
I believe this can be implemented with a single high-level rule, which says that every URI that points to an object of type TopLevel SHOULD be able to be dereferenced.

We don't need to include child objects, since they already MUST be able to be deferenced.

**Comment by cjmyers** [comment]
I don't think this is a good idea.  The problem with combining rules is it makes them a lot less clear when reported, which I think is a higher priority than making the list of validation rules smaller.

**Comment by jakebeal** [comment]
I don't believe the two are in conflict if one implements it as a table rule. All the information that is needed is already there in Table 22.

**Comment by cjmyers** [comment]
Ok, I'm still pretty unsure how the validator will be implemented, but I guess you will work with Tom and the other library developers on that one.  May be a good thing to discuss on Monday.

**Comment by jakebeal** [comment]
Fix added into #440
