### ISSUE TITLE
Should Sequences be TopLevel objects?

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#181]
A student of mine is working on sorting search results on SynBioHub using the Page Rank algorithm.  One interesting observation we found is that when searching for LacI that the LacI_sequence object was sorted ahead of LacI ComponentDefinition for the CDS.  The reason for this is that while the LacI CDS is used in a lot of designs, the sequence object is referenced by the CDS CD object, so it actually ends up with a higher page rank than the CDS.  This looks a bit odd, since the Sequence object is not likely the one the users are looking for.

This is actually a symptom of a larger issue, which is that having Sequence objects be TopLevel objects is a bit problematic.  A bit of history, the reason we decided to make them TopLevel objects is that we thought this could avoid having to copy large sequences that are perhaps annotated in alternative ways.  However, this use case does not appear to have shown up.  Most Sequence objects do not stand alone without a ComponentDefinition referencing them, and it has to date always been a single ComponentDefinition referencing them.

Since search in SynBioHub returns TopLevel objects matching the search result, these Sequence objects show up in search results, and as mentioned above can be ranked high.  They also show up in Collections for submissions.  The other problematic issue is that when you delete a ComponentDefinition in SynBioHub, you end up with a “ghost” Sequence object.  Since it is a TopLevel object, it is not a child object of the ComponentDefinition, so it should not be deleted when the ComponentDefinition referencing it is deleted.  Compare this with, child objects like SequenceAnnotations which are deleted with the parent ComponentDefinition.

One temporary solution to this in SynBioHub is to treat Sequences like child objects.  In other words, do not show them in search results, and delete them when their parent CD is deleted.  So, my questions are:

1) Does anyone see a problem with treating Sequences like children of ComponentDefinitions in SBH?
2) If you agree with 1, should SBOL 3 change Sequences to be children of ComponentDefinitions?
3) If you agree with either 1 or 2, what about Models for ModuleDefinitions?  Similar arguments can be made to make Models children of ModuleDefinitions.

**Comment by jakebeal** [comment]
I oppose this for the reasons stated on the sbol-dev list:
>I am concerned about workflows here when dealing with FASTA and other pure sequence inputs. A FASTA file doesn't naturally convert into a ComponentDefinition, it naturally converts into a Sequence, and there's a LOT of FASTA data out there---and ongoing use cases (including in some projects at BBN) where it makes sense for us to be working with FASTA or equivalent sequence information.
>
>Thus, I would oppose general demotion of Sequence to no longer be a TopLevel object.
>
>Instead, I would advocate upgrading the SBH user interface to automate the common case of "delete the CD, then delete the associated sequence" during manual deletion.  For example, when deleting a CD, the confirmation box could have a checkbox (checked by default) for "Delete associated sequence if unused by other Components?"

**Comment by jakebeal** [comment]
Can we close this one now?

**Comment by cjmyers** [comment]
Yes, we can.
