### ISSUE TITLE
Extra comma (or missing word?) in SBML bibliography entry

### ISSUE THREAD

**Issue by mikebissell** [SynBioDex/SBOL-specification#183]
SBOL 2.2.1, p91, line 21 has an extra comma. Not sure if this also indicates a missing word in this citation. The comma following the colon is also weird.

`Hucka, M., Finney, A., Sauro, H. M., Bolouri, H., Doyle, J. C., Kitano, H., , the rest of the SBML Forum:, Arkin, A. P., 21 Bornstein, B. J., Bray, D., Cornish-Bowden, A., Cuellar, A. A., Dronov, S., Gilles, E. D., Ginkel, M., Gor, V., Goryanin, 22 I. I., Hedley, W. J., Hodgman, T. C., Hofmeyr, J.-H., Hunter, P. J., Juty, N. S., Kasberger, J. L., Kremling, A., Kummer, U., 23 Novere, N. L., Loew, L. M., Lucio, D., Mendes, P., Minch, E., Mjolsness, E. D., Nakayama, Y., Nelson, M. R., Nielsen, 24 P. F., Sakurada, T., Schaff, J. C., Shapiro, B. E., Shimizu, T. S., Spence, H. D., Stelling, J., Takahashi, K., Tomita, M., 25 Wagner, J., and Wang, J. (2003). The systems biology markup language (SBML): a medium for representation and 26 exchange of biochemical network models. volume 19, pages 524–531. Oxford University Press (OUP).`

**Comment by jamesscottbrown** [comment]
Weirdly, the bibtex downloaded using the Cite link on the [OUP page for the paper](https://academic.oup.com/bioinformatics/article/19/4/524/218599) includes "and the rest of the SBML Forum:" in the name of each author, whereas the BibTeX returned from the ``dx.doi.org`` endpoint with the header ``Accept: application/x-bibtex`` only includes it once (in the incorrect position shown above).

I'm just waiting for pdftex to recompile the document to check my fix before I commit it ...
