### ISSUE TITLE
Standardize graphical style of all specification diagrams.

### ISSUE THREAD

**Issue by mikebissell** [SynBioDex/SBOL-specification#188]
The spec currently contains many diagrams. These diagrams are drawn in heterogeneous graphical styles, with a variety of typographic conventions at play. It would improve the spec's general impression of professional polish if we would settle on just one style, and standardize on just one tool for editing diagrams, and then convert the other diagrams to this uniform style.

I would also recommend having a typesetter or print graphic designer eyeball whatever style we settle on. In just a few minutes, a pro can make fine adjustments, seemingly trivial revisions, that make a big impact on perceived polish. 

Our standard diagram style should look good alongside, and appear sufficiently consistent with, the surrounding text.

There are specific points of polish we should address in most the existing diagrams. (I can provide specific examples if somebody wants to contact me offline.)

To start, we could index all the diagrams, associate them with the tools used to create each, and link each to its source code (if external).

**Comment by jamesscottbrown** [comment]
Most (but not all) of the diagrams are created in [UMLet](https://umlet.com/), with their source files in the [``/umlet_source``](https://github.com/SynBioDex/SBOL-specification/tree/master/umlet_source) directory.

**Comment by jamesscottbrown** [comment]
The other figures are in ``images/``. Here's a summary:

| Image file                | Software used     | Source file           | Creator                  |   |
|---------------------------|-------------------|-----------------------|--------------------------|---|
| format-comparison.pdf     | PowerPoint        | format-comparison.pdf | Jake Beal/Goksel Misirli |   |
|  MapsTo_Diagram3.png      | PowerPoint?       |                       | Goksel Misirli           |   |
| OverviewFig-v4.png        | PowerPoint?       |                       | Goksel Misirli           |   |
| OverviewFigforSpec-v7.png | PowerPoint?       |                       | Goksel Misirli           |   |
| sbol_v1_to_v2.pdf         |  OmniGraffle      |                       | James Scott-Brown        |   |
| standard-evolution.pdf    | Adobe Illustrator | standard-evolution.ai | Chris Myers              |   |
| toggle-highlevel2.pdf     | PowerPoint        | toggle-highlevel.pptx | Chris Myers              |   |
| toggleswitch_modular.png  | PowerPoint?       |                       | Goksel Misirli           |   |
| toggleswitch_modular2.png | PowerPoint?       |                       | Chris Myers              |   |

**Comment by jamesscottbrown** [comment]
@goksel do you still have the source files for MapsTo_Diagram3, OverviewFig-v4, OverviewFigforSpec-v7, and toggleswitch_modular?

@cjmyers do you still have the source file for toggleswitch_modular2?

**Comment by cjmyers** [comment]
I think @tramyn created this one, unless I'm mistaken.

**Comment by tramyn** [comment]
@jamesscottbrown: Sorry James, I no longer have the source file for the toggleswitch_modular2 figure.

**Comment by jakebeal** [comment]
I believe this is now moot with SBOL3, which has made a more unified style.

**Comment by cjmyers** [comment]
Agreed.
