### ISSUE TITLE
SEP 004: Add contextual role properties to SequenceAnnotation and Component

### ISSUE THREAD

**Issue by mikebissell** [SynBioDex/SBOL-specification#19]
I propose adding the property SequenceAnnotation.roles to SBOL 2.0:

[Update: I (MB) now endorse adding optional role(s) to Component as well. See below.]

"""
The roles property

The roles property is an OPTIONAL set of URIs that clarifies the potential function of a region described by a SequenceAnnotation. 

Note that it is also possible to specify the role(s) of a SequenceAnnotation's underlying ComponentDefinition. However, the role(s) of such child entities cannot always be determined outside of a specific context. If a child Component is given for a SequenceAnnotation, then the SequenceAnnotation's roles property specifies the _contextually determined_ role(s) of that Component.

The roles property of a SequenceAnnotation MAY contain one or more URIs that MUST identify terms from ontologies that are consistent with the types properties of all related ComponentDefinitions. Please refer to ComponentDefinition.roles for a discussion and examples.
"""

My rationale:

We need this in SBOL 2.0 before we can encode high-level construction recipes. In our case, it's often impossible to specify the role of an oligo outside of a context. For example, exactly the same oligo might serve as a PCR amplification primer or an LCR bridging oligo, depending on how it is used in context. Those SequenceAnnotation.roles can serve as key declarative instructions to software that implements an automated DNA construction service.

In a recent conversation with Chris Myers, Matthew Pollock supplied a second example. He wrote, "The role that a CD is designed for is not always exactly the role that it is used for within a larger design (how often do you hear variants on 'well I pulled this part off the shelf to act as a spacer because I know it's transcriptionally [inert between] promoter and RBS'), and in some cases you want to sketch a design without mentioning any particular child components at all e.g. genbank or swissprot rendering."

**Comment by jakebeal** [comment]
Discussion of this proposal is contained in the thread: https://groups.google.com/d/msg/sbol-dev/DvcaAgBV5CE/ijcR58b1XfkJ

**Comment by jakebeal** [comment]
Summary of discussion:
* Can we have role by *only* per-instance, and not on ComponentDefinition?  No: that prevents statements like "this is expected to be a promoter" and prevents expression of collections like the Anderson promoter library.
* If role is duplicated, should type be as well? Probably not, since role may change in context while type describes the physical nature of the entity (e.g., DNA vs. RNA vs. protein), and generally does not.
* A fully-worked example would be useful.
Thus far, no particular controversy.

However, there is a question: should the contextual role be added to SequenceAnnotation, Component, or ComponentInstance?
* Argument for ComponentInstance: ComponentDefinition / intendedRole is an equivalent relationship to ComponentInstance / contextualRole.
* Argument for Component: unclear whether a FunctionalComponent will ever need a contextual role.
* Argument for SequenceAnnotation: Mike's original proposal, SequenceAnnotation is analogous to Participation, closer structure to GenBank, also instances should not exist.

These questions are unlikely to be rapidly resolved and may involve significant changes to the data model; therefore, I am recategorizing this issue from Version 2.0 to Version 2.1.

**Comment by jakebeal** [comment]
Actually, this should be resolvable by 2.0.1; in the mean time, Mike should be able to experiment using annotations, and there's a fast path for upgrade.

**Comment by mikebissell** [comment]
Jake requested,
"Please update my summary of the state of debate on the issue accordingly. [Jake Beal, 6/29/2015]"

And so here is a digest of the debate that ensued on the SBOL list. I have omitted my long-form presentations of use cases, which I hope to add later, in separate comments.

"[T]here is quite a bit of analogy between SequenceAnnotation on the sequence-level and Participation on the function-level. So, in terms of "data model symmetry", I think it may make more sense to put Role on SequenceAnnotation rather than on Component/Instance. [Raik Gruenberg, 6/27/2015]"

"I would also prefer SequenceAnnotation rather than Component/ComponentInstance.  However, I would not object strongly to having it in BOTH places.  My original use case was for a simple GenBank translation without the need for Components at all to be created.  This would be lost by putting it on Component/ComponentInstance.  While Mike’s use case would not be lost, since he could create SA with GenericLocations which reference the Component that he wants to give a role to.  However, I can see why this overhead may not be appealing which is why I would be okay with it ALSO being on Component or ComponentInstance. [Chris Myers, 6/27/2015]"

"Well, as a side comment, SA could and should point to ComponentDefinition directly, then there would be no question where to put the Role field. Things (instances?) being as they are, allowing Role both on SA and on ComponentInstance sounds like a great compromise but may actually create confusion (e.g. two conflicting Roles on both; hidden assumption of some software that Role is on Component when it can also be on SA; etc.). Generally, we should try to avoid different solutions for one and the same problem. [Raik Gruenberg, 6/27/2015"

"I think it is pretty simple still.
1) Put role on SA, pro: simple GenBank conversion, con: need a SA to give an instance a context dependent role.
2) Put role on Comp/Inst, pro: can give instance context dependent role, con: do not get simple GenBank conversion
3) Put role on SA & Comp/Inst, pro: get both advantages, con: can have conflicting roles (possible solution, restrict to one location)
[Chris Myers, 6/29/2015]"

"Another solution would be to merge SA into Comp, and make the pointer back to CD optional. But that's definitely not a version 2.0 fix. I'm just adding this for completion. [Matthew Pocock, 6/29/2015]"

"I would be ok with moving this issue to a vote for 2.0.1.  The change is minimally invasive.  There does seem to be a little disagreement about where to add the new "roles" property.  None of the options are perfect, but I can live with any of the 3 options below. [Bryan Bartley, 7/01/2015]"

...also in the same message, Bryan inquired whether copying CDs, rather than incorporating them by reference, might be the way to go:

"I would like to know the answer to Jake's earlier question, though.  Could the current data model handle Mike B's use case?  For example, what is the cost of simply defining a new ComponentDefinition when the same part is used in different contexts? [Bryan Bartley, 7/01/2015]"

Matthew offered one answer:

"You would have two CDs for two different uses of the same primer/oligo, presumably pointing to the same sequence(s), with individual roles. This is legal, but it isn't obvious for a 3rd party that they should be looking out for this happening. Which one of these several CDs for the exact same primer is the 'real one' that is decorated with where it is in the fridge and all that other useful stuff? So in summary, you can store the data now, but it isn't clear to others what it means. Capturing the same knowledge with a SA role is explicit, and avoids multipying otherwise equivalent CDs. [Matthew Pocock, 7/01/2015"

MB also replied to Bryan's question (see original message for "[...]" details):

"Sorry, we considered this option, and it would not serve our purposes. Here are a few reasons.
1) Replicating ComponentDefinitions during serialization is space-inefficient. [...]
2) Copying ComponentDefinitions denormalizes our catalog of designs. [...]
3) Copying ComponentDefinitions stresses the referential integrity of our data model. [...]
4) Needless replication is computationally inefficient, and it slows down processing. [...]
[Mike Bissell, 7/01/2015]"

**Comment by mikebissell** [comment]
After prototyping this change, I realize why some may want to add BOTH SequenceAnnotation.roles and Component.roles. I am sympathetic. However, there might a partial workaround that requires only SequenceAnnotation.roles, which I consider below..

One argument in favor of putting roles in both places:

SBOL2 permits a parent ComponentDefinition to contain Component(s), SequenceAnnotation(s), or both. In cases where this parent's DNA Sequence has not yet been determined, it may not be feasible to embed a SequenceAnnotation cleanly into the parent ComponentDefinition, because there is no Sequence to annotate yet.

I should note that it is routine, in a genetic compiler, to encounter states where the composition of a tree of ComponentDefinitions is known, but where the parent DNA sequence has yet to be determined (through compilation).

Nevertheless, it may still be necessary for strain engineers to specify the context-specific role(s) of a child Component, role(s) which are *not necessarily identical* to the "essential" role(s) currently assigned to the child ComponentDefinition. (Can we all agree that roles are potentially determined by context?) For example, a construction service interface might require site-specific flags, in the form of roles, indicating how the customer intends the service to integrate this sub-Component into the parent ComponentDefinition. Concretely, I need to classify sub-Components with site-specific roles flags which map elements of my nice, recursively defined SBOL2 recipes onto low-level process steps, types, and operations inside existing construction services whose data model predates SBOL2.


A (weak) argument against putting it in both places:

We might be able to work around the need to put roles on a sub-Component by using a SequenceAnnotation, containing SequenceAnnotation.role(s). This "placeholder" SequenceAnnotation would point to the Component in question, thus annotating it with role(s), without pointing to a Sequence, which is not yet known. There is a problem with this workaround: **at least one** SequenceAnnotation.location is *required* by SBOL2. We *could* relax this requirement from 1..many Location child per SequenceAnnotation, relaxing it to permit 0..many Locations, but that would further muddle the purpose of SequenceAnnotation. SA would become something more like a SequenceOrComponentAnnotation. (My take on this option: yuck. I don't like it. Permitting multiple Locations per SequenceAnnotation has already been pretty contentious.)


My endorsement: stick roles on both.

Side comment: in an alternate universe, we might have merged SequenceAnnotation and Component.

**Comment by jakebeal** [comment]
An important thing that needs to be added as a part of the SEP is a Best Practice.

* SA roles should be used to describe emergent or consequent features of a design, e.g., "putting these pieces together accidentally created a promoter" or "this is a start codon"
* SA roles should *not* be used in place of a Component to describe an *intentional* feature, e.g., "we want a Promoter at this location"

This is because people aren't necessarily used to CAD tools, and need guidance to help creating their modularity.

**Comment by jakebeal** [comment]
This is SEP 004

**Comment by mikebissell** [comment]
The following comment went out over email today, but I've copied it here FTR, hoping that it might help the community evaluate the details of SEP 004. I think I might need to revise 004 to include a few serialization examples as well as a concise list of required operations on sets of roles in order to make this SEP easy to swallow.

For some background on SEP 004, here's my perspective on role classifications.

I'd like to suggest that putting roles on isolated ComponentDefinitions may have been a necessary concession to human factors, but perhaps it was not an accurate decision with respect to modeling.

If something has a role, then it has that role only in some context.

An isolated module like a ComponentDefinition does not specify its context. The whole point of defining a module is that we should be able to use it in many contexts.

So why should ComponentDefinitions have had roles at all? Interpreting a role requires a reference to a context, but encoding assumptions about context into a ComponentDefinition violates modularity. The only reason to put roles on a ComponentDefinition is that humans who operate CAD systems like to design parts against a background of assumptions about how they intend to use those parts, and so when they save a part to a file, human designers like to encode those intended uses along with the part sequence. We like to say, "I think this is a marker sequence prefix fragment," even though the selection marker will only function if this part is integrated alongside its intended suffix fragment. In SBOL2 we save these declared uses as ComponentDefinition.role elements, but those roles actually encode the designer's tacit assumptions about activity in context. Those assumptions might later prove to be false, but we'll happily keep using that part's DNA, because that part is in physical inventory, and we'll just ignore the original role declarations. If the same part is later repurposed in a different context, its roles must be reevaluated, perhaps discarded. SEP 004 allows us to do this.

When the designer of a ComponentDefinition declares its roles, those are merely the roles imagined by the designer at the time. Later, when a genetic construct is incorporated into an assembly, or into a genetic compiler build product, or into a living organism, then its roles may be further determined or modified, as the context is defined. Hence the precedence stipulations in SEP 004.

You might put a part into a repository that is tagged with some biological roles, because you imagine that you might use that part in a specific logical or physical context. But that context is not the only context in which a modular part may be used. In a different context, that module could play an entirely different role -- or none at all. That's why SEP 004 allows us to strip declared roles in context -- and optionally substitute new ones.

In a different experiment, I might appropriate that part for a new purpose, discarding its intended roles and substituting the correct roles, as determined by my operational assembly context, or by my biological host context, or by my computational compilation context. (There are lots of compiler symbols that classify only the compositional relationships between genetic components, and *not* the components themselves.)

The same oligo does different things, depending on where you put it. It doesn't matter what the isolated oligo says it was made for in its ComponentDefinition. SEP 004's proposed XML serialization would allow us to express these differences.

In practice, I find that the ComponentDefinition roles are merely a cataloging convenience, whereas the contextual roles are the ones that really matter.

**Comment by graik** [comment]
Let me paste a summary of my counter argument. I am not sure spreading the discussion across two mailing lists and two issue trackers is helpful though :) Better would be to stick to the SEP 004 and sbol-dev.

I sympathize with the importance of context for biological function. But I think this discussion is too abstract. A building block classified as "fluorescent protein" will in 99% of the cases be used in order to get a fluorescent protein. The same is true for most other parts. 

> In practice, I find that the ComponentDefinition roles are merely a cataloging convenience, whereas the contextual roles are the ones that really matter.
>

I agree, except of the "merely". But in this case, there is absolutely no need for a special role container or a "empty role set" construction on the level of Component or SA. Why? Because it is implicitly understood that any roles given to CD are for functional part classification only. If there is no role given to SA or Component, that simply means we don't have any further information about design intent. Whether or not a software then chooses to completely ignore the information at the CD level can be left to the implementation and will vary depending on what problem this software is trying to solve. 

There are further arguments against the "empty container" solution, namely:
* Surprise factor: not giving any role to SA has exactly the opposite consequence of giving an empty set of roles.
* Container solution means it is not possible to *add* a role at the SA or Component level -- as soon as a single role is added, all ComponentDefinition roles are considered removed and would need to be re-stated. Very inelegant.

**Comment by mikebissell** [comment]
People following this issue, please note that SEP 004 has evolved rapidly in response to in-depth review on the libsbol-team list, where we have consolidated the debate per Raik's suggestion above.

**Comment by mikebissell** [comment]
Update: removed Needs SEP. SEP 004 was approved: https://github.com/SynBioDex/SEPs/blob/master/sep_004.md

I am nearly done integrating SEP 004 into model.tex.

**Comment by cjmyers** [comment]
I believe this issue is now completed once the pull request is accepted.

**Comment by jakebeal** [comment]
Completed.
