### ISSUE TITLE
Problem with encoding URIs

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#191]
The URIs for DNA, RNA, and Protein sequences no longer dereference correctly:

http://www.chem.qmul.ac.uk/iubmb/misc/naseq.html
http://www.chem.qmul.ac.uk/iupac/AminoAcid/

**Comment by jakebeal** [comment]
I would suggest switching all of the URIs in the table to EDAM via identifiers.org:
- DNA (implicitly IUPAC): http://identifiers.org/edam/format_1212 
- RNA (implicitly IUPAC): http://identifiers.org/edam/format_1213
- Protein (implicitly IUPAC):  http://identifiers.org/edam/format_1208 
- SMILES: http://identifiers.org/edam/format_1196

**Comment by cjmyers** [comment]
We just discussed this and decided this would be a breaking change, so it should be delayed to SBOL 3.0.  We should though add to the specification links (if we can find them) that define these encodings, which is something we lost.

**Comment by palchicz** [comment]
Closing this issue as redundant with https://github.com/SynBioDex/SBOL-specification/issues/10

**Comment by palchicz** [comment]
Also, splitting out https://github.com/SynBioDex/SBOL-specification/issues/208 to address @cjmyers's concern above linking out to some definition of these encodings.
