### ISSUE TITLE
Include 3.0 validation rule from SEP 013

### ISSUE THREAD

**Issue by palchicz** [SynBioDex/SBOL-specification#197]
[SEP 013](https://github.com/SynBioDex/SEPs/blob/master/sep_013.md#specification) contains a validation rule specifically for 3.0

> If a Component has one or more locations, the sequence range or sequence ranges defined by Component.sourceLocation MUST add up to exactly the same length as the range(s) covered by the Component.location record(s).

This needs to be incorporated into the spec

**Comment by PrashantVaidyanathan** [comment]
It looks like this issue has been incorporated into the spec in this PR [https://github.com/SynBioDex/SBOL-specification/pull/201](https://github.com/SynBioDex/SBOL-specification/pull/201)
