### ISSUE TITLE
Having version numbers at the end of URLs is not compatible with RDF tools

### ISSUE THREAD

**Issue by dissys** [SynBioDex/SBOL-specification#198]
RDF/XML adopts XML local names to create URIs and that means we should not have numbers at the end. Currently we use these numbers to represent version numbers. For example regarding the part "igem.org/promoterA/1", SBOL allows using 1 at the end to specify the version number. However, this causes issues in Semantic Web related tools. I suggest not to use the version numbers at the end of URIs to be compatible with the RDF standard and other tools. 
https://www.w3.org/TR/rdf-syntax-grammar/  
https://www.w3.org/TR/1999/REC-xml-names-19990114/#NT-NCName 

Secondly, having local name "1" means that the namespace to refer to would be igem.org/promoterA. This means having a namespace declaration for each part rather than having a single namespace for the organisation.

Potential solutions:
- Use underscore to separate the id from the part. E.g.
igem.org/promoterA_1
This solution may be backward compatible since it still has the version number, which is still at the end. The local name would be promoterA_1.
- Not to have any version number in the URI at all and use different URIs for different versions. The version info would be a property of an SBOL entity. 
- Swap the entity id and version id
E.g.:igem.org/1/promoterA. 
This also has issues. Now we have the namespace igem.org/1/ and igem.org/2/ to refer to version 1 and 2 parts respectively.

**Comment by goksel** [comment]
I created the issue for SBOL 3.0.

**Comment by goksel** [comment]
Please also see the notation here for local names:

[4] | NCName | ::= | (Letter \| '_') (NCNameChar)* | /* | An XML Name, minus the ":" */
-- | -- | -- | -- | -- | --
[5] | NCNameChar | ::= | Letter \| Digit \| '.' \| '-' \| '_' \| CombiningChar \| Extender

https://www.w3.org/TR/1999/REC-xml-names-19990114/#NT-LocalPart

**Comment by jakebeal** [comment]
I believe this is now resolved in SBOL3

**Comment by cjmyers** [comment]
Agreed
