### ISSUE TITLE
Best practice file extension

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#20]
In various implementations, SBOL files have variously been given the extensions .sbol, .rdf, and .xml
What is the preferred best practice for SBOL extensions?

**Comment by jakebeal** [comment]
SBOL14 meeting consensus: best practice is to give the extension of the actual serialization used, e.g., .xml, .json, .ttl

**Comment by mehersam** [comment]
There is now a paragraph in the second paragraph to closing in the Serialization sectin explaining the preferred file extension and the motivation behind the idea.

**Comment by mehersam** [comment]
Done.
