### ISSUE TITLE
Support InChI for small molecules?

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#202]
Some recent exposure to chemists has suggested that the much of the chemical community now prefers [InChI](https://en.wikipedia.org/wiki/International_Chemical_Identifier) representations over SMILES (our current recommendation for small molecule sequence descriptions).  InChI is more expressive, and there are converters between the formats (e.g., https://www.chemspider.com/InChI.asmx).

Should we change our recommendation or should we recommend any and all of SMILES, InChI, or InChIKey as alternates?

**Comment by jakebeal** [comment]
Related to #185

**Comment by cjmyers** [comment]
Table should include these things as well as perhaps BpForms to restrict the URIs used in the encoding field.  Though no position should be taken on the best encoding for anything except DNA/RNA/Proteins.

**Comment by cjmyers** [comment]
Can use EDAM for the encoding URIs
