### ISSUE TITLE
Reconsider names or definitions of fields with same name

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#216]
Some field names (e.g. type, role) appear multiple places, but have different definitions.  These should either have different names or the same definitions.

**Comment by goksel** [comment]
No strong opinion based on how they are currently used. Component, LocalSubComponent, ExternallyDefined have the type property and the definitions in the spec seem to be clear.  Activity and Measure entities also have the type property though. The role property's use indicates biological role across the use in Component, Participation and Feature.

**Comment by cjmyers** [comment]
Closing
