### ISSUE TITLE
Reconsider recommendations about URIs.

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#217]
Reconsider recommendations about URIs.

1. Should all URIs be compliant?
2. If so, do we need to serialize displayId, version, persistentIdentity?
3. If not, should we eliminate the idea of compliant URIs and let them be anything?  If so, what are the ramifications of this decision on libraries and software?
4. If we keep compliant URIs, should we rethink where the version comes in the URI?

**Comment by bbartley** [comment]
One thing I really like about compliant URIs is that it facilitates a simple and easy interface.  For example, in pySBOL, I can reference a sequence annotation using its displayId only, as follows:
```
cd.sequenceAnnotations['ann_1']
```
In my own experience as a user, I have never wanted to reference or retrieve a child object from the graph directly using its URI.  I always want to reference it from the context of the parent object.  Thus, I should never have to think about a child object's URI.  Rather, it should be handled automatically for me, either by following the convention of compliant URIs or by using anonymous RDF nodes.

**Comment by cjmyers** [comment]
Yes, exactly!  This was one of our main reasons for doing this.

**Comment by jakebeal** [comment]
Could we consider a hybrid solution, in which child objects have a required URI relationship to their parents, but where we relax the restrictions on parent object URIs?

We also need to remove the difference between "SBOL compliant" and "SynBioHub compliant" URIs, either by strengthening the requirements in the standard or by making SynBioHub more permissive.

**Comment by cjmyers** [comment]
I don’t think so.  The point is that if you set a default URI prefix, you can create and fetch objects using their displayId and version.  This would not work, if we lost the relationship between these and the URI.  I think the scheme needs tweaking like how the version is included, but I don’t think it should be abandoned.

Also, not sure what you mean by SynBioHub compliant.  SBH has a particular form of URI, but it accepts SBOL submissions even with non-SBOL compliant URIs.

**Comment by jakebeal** [comment]
SynBioHub restricts the depth and structures of URIs: you always have precisely two levels, such that more complex URI structures get compressed and lost if you want to put them in SBH, which has been a problem for us with respect to naming.

**Comment by cjmyers** [comment]
Ok, I see your point.  It is not the URIs that it consumes it restricts, but it is the URIs that it creates which are restricted.  All software that mints its own URIs must decide a scheme for doing so to ensure URI uniqueness, and this is the scheme we came up with.  If you have examples of what you are trying to do and why it is problematic, you can put those on the SBH tracker.  The SBH URI minting scheme though is not part of the SBOL specification.  Indeed, SBH must be capable of accepting any form of URI, which has been a source of challenge, since it is much harder to convert arbitrary URIs into a new namespace while maintaining URI uniqueness.

**Comment by jakebeal** [comment]
A simple example would be the samples, implementations, and attachments in SD2, which end up with names like: https://hub.sd2e.org/user/sd2e/experiment_test/experiment0x2etranscriptic0x2er1brvabq9fjgd_r1bry2xb8scz4_group_0/1
and
https://hub.sd2e.org/user/sd2e/experiment_test/experiment0x2etranscriptic0x2er1brvabq9fjgd_r1bry2xb8scz4_sample0x2etranscriptic0x2eaq1brz6m2f325u/1
and 
https://hub.sd2e.org/user/sd2e/experiment_test/s30x3a0x2f0x2fsd2e0x2dcommunity0x2fuploads0x2ftranscriptic0x2f2018080x2fnovel0x2dchassis0x2fr1bzc55fpurbj0x2fC10_S32_R2_0010x2efastq0x2egz/1
We can't give them more structured URIs, so we end up concatenating all of the levels of structure together into a nightmare name with lots of opportunities for things to go wrong.

**Comment by cjmyers** [comment]
You can give them more detailed URIs, but SBH will indeed create URIs like those you show below.  In theory, SBH could be adapted to preserve the paths you want.  Feel free to add an issue to the SBH tracker requesting this.  There were some technical reasons why this was not done initially, but we might be able to overcome them.  The key thing will be to come up with a clear URI minting scheme for SBH.  Maybe something like:

Initial: <Your URI prefix>/<path>/<displayId>/<version>

SBH: <SBH URI prefix>/user/<username>/<collection>/<path>/<displayId>/<version>

where <path> can be any arbitrary string of <id> broken by / delimiters.  The key point though is that because URIs are not required to be compliant.  I cannot know for certain I will get URIs in the form above (Initial), which means SBH needs fallbacks for when they are not structured in this way.  Requiring SBOL to have compliant URIs would actual open up the doors to things like this to be fairly easy to support. Being able to simultaneously support unstructured URIs which can literally be any string from “foo” onwards is a huge source of complexity and bugs.

**Comment by jakebeal** [comment]
Done in SBOL 3
