### ISSUE TITLE
Specification needs better examples

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#22]
Swapnil wrote:

The Examples section is great and inadequate at the same time (pp. 43 - 48). I think we need a lot more examples that illustrate how to use the standard.
As a user, I began reading parts of the standard, then quickly skipped to the examples. I am still interested in simple use cases -- collections of components, 
design libraries, annotations etc., and not so much the models, functions, etc. Should I just be using 1.1 or does 2.0 help make my life easier too? More broadly,
what synbio processes and tools are the prime use cases for the new features?

[transferred from mailing list]

**Comment by goksel** [comment]
Added serialization examples to the "Examples of Serialization" section.

**Comment by jakebeal** [comment]
Duplicate of #9.

**Comment by palchicz** [comment]
closing since it is a duplicate
