### ISSUE TITLE
Move to compact identifiers from identifiers.org

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#222]
See note below:

Hi @cjmyers ,
There are several ways identifiers.org resolution services:

http://identifiers.org/<compact:identifier>
http://identifiers.org/<<provider_code>>/<compact:identifier>
Identifiers.org registry has the advantage of allowing multiple providers per namespace, enabling, this way, a failover / choice mechanism.

Providers reliability information is internally collected over time, and it plays a role in the resolver decision making when resolving a compact identifier request.

To take full advantage of this, we encourage our users to use the stable URL 'http://identifiers.org/compact:identifier'.

In the case a user would like the resolver to 'force' the resolution to a particular provider, a 'provider code' may be supplied in the URL, e.g. 'http://identifiers.org/biomodels.sbo/SBO:0000169' is requesting the resolver to resolve compact identifier 'SBO:0000169' to provider 'biomodels.sbo'.

This way of requesting compact identifier resolution does not count on the failover / multiple choice mechanism mentioned above, and it results on not stable URLs, as providers may no longer be in service, or they may choose to change their provider code.

In the case of SBO, the resolved URL ‘https://www.ebi.ac.uk/sbo/main/SBO:0000169’ you mention in your comment, is associated to a resource with provider code ‘ebi’.

After a conversation with Biomodels team, there seem to be no problem on changing this provider code to “biomodels.sbo”, as a temporary fix for those legacy URLs, but in the long term, we really encourage our users to make use of identifiers.org stable and reliable URLs for compact identifier resolution.

Thanks again for your feedback, and please, don’t hesitate to reach out to us in case you have any other question.

Kind Regards,
Manuel

**Comment by jakebeal** [comment]
Closely related to #366
