### ISSUE TITLE
Need a way to specify the join order for a set of Locations

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#224]
When there is a set of Locations associated with a SequenceAnnotation (or Component in SBOL3), we need a way to specify the order they are to be joined.  For example,

join(complement(A..B),complement(C..D)) is the same as complement(join(C..D,A..B))

The former can be specified with SBOL locations, which put the complement on each range, but the later cannot.  However, if we convert the later to the former, we need to be able to specify that  complement(A,B) should come before complement(C,D).

**Comment by udp** [comment]
@cjmyers, this is resolved in SBOL3 now right?

**Comment by cjmyers** [comment]
Yes, should be.
