### ISSUE TITLE
Is Module / ModuleDefinition more complexity than necessary?

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#24]
Is has been suggested that the Module / ModuleDefinition complex may introduce unnecessary complexity into SBOL2.  Suggested alternatives include:
- Replacing Modules with Interactions, but expanding the types of Interactions to a new and much more complex set based on intended function rather than biological activity (e.g., "NOR gate")
- Replacing Modules with links to SBML

**Comment by udp** [comment]
Fixed in SBOL3 (Module has been merged into Component)
