### ISSUE TITLE
Definition / Instance distinction needs to be better explained

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#26]
Both the motivation  of the definition vs. instance distinction and its implementation in the data model need to be explained in a way that is accessible to SBOL users who are not computer programmers.

**Comment by jakebeal** [comment]
Make sure we add an example to illustrate.

**Comment by cjmyers** [comment]
Mike Bissell addressed this one by revising Section 5.2 to define Component/FunctionalComponent/Module as pointer classes.  He then updated the text near the end of the Overview section to describe these as such.  I've reviewed it but one more reviewer would be good before closing.

**Comment by jakebeal** [comment]
Chris asked me to add another set of eyes to this change; I tweaked the wording a little, and think it's now good.
