### ISSUE TITLE
Ensure that users can ignore features they do not need

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#27]
SBOL should allow users to largely ignore aspects of the specification that are not needed for their application.  For example, somebody who is building an oligo-assembly-planning tool should be able to largely ignore everything about modules and models.

We need to make sure that this is actually the case, and that it is clearly explained in the specification.

**Comment by jakebeal** [comment]
An example of a workflow concern in this area: consider a structural tool that edits sequences for improved assembly, then a functional tool that wants to take these new sequences back in.  The structural tool needs to either be function-aware or else mark with "was derived" and have the functional tool re-integrate.

We need to observe interactions in the wild to see what happens.

**Comment by jakebeal** [comment]
SBOL14 summary: this probably needs to be addressed through clear specification of what "compliance" means at various different levels (i.e., ex/im, structural, functional), and should be written into the spec.

**Comment by cjmyers** [comment]
Done though needs another set of eyes.

**Comment by jakebeal** [comment]
Note: this is addressed in the new "Compliance" section of the spec.
