### ISSUE TITLE
Create cover page with authors and abstracts

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#29]
Create the cover page with authors and abstract.

**Comment by jakebeal** [comment]
Please don't forget to assign milestone, tags, and person (where applicable) to the issues that you open: otherwise they may end up untracked.

**Comment by jakebeal** [comment]
Fixed to nick, who's the actual assignee

**Comment by nroehner** [comment]
I've created the cover page here:

https://www.overleaf.com/3043483knjcjm
