### ISSUE TITLE
Require role on participation

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#33]
Currently role is not required on participation.  Perhaps, it should be required, since otherwise no role is ambiguous.  To make this work though, we must have an SBO term for unknown participant role.

**Comment by graik** [comment]
I very much agree. Role should be required.

This is a good moment to talk about Role in general. We have found very good reasons to add Role to SequenceAnnotation and perhaps also FunctionalComponent and Component. There is a lot of symmetry here. SA, FC, Participation and Component all are wrappers around ComponentDefinition (directly or indirectly) that place this ComponentDefinition into a functional or structural context. It makes sense that they all have a Role field. For maximal consistency, Role should then perhaps be required in all four cases.

**Comment by cjmyers** [comment]
In order to keep this a 2.1 issue and not a 3.0 issue.  I suggest that we do add role to the SA, FC, and Component, but we stop short of requiring it, since this would invalidate 2.0 files missing roles.  Instead, let’s make this a best practice.  The library validator would then warn you when these are missing.  We will also provide a strict mode that makes a missing role a failure.  This way we can still read 2.0 files safely, but we can also move towards requiring it going forward.

Actually, once we do introduce a 2.1 namespace, this require flag could default to true for 2.1 files.

**Comment by graik** [comment]
Sounds like an excellent plan. I can prepare an SEP later today.

**Comment by jakebeal** [comment]
The interpretation of the editors, in discussion at SBOL14, is that this is a typo in the spec.  Furthermore, since nobody is intentionally creating participations without roles at present, there is no backward compatibility issue.

**Comment by cjmyers** [comment]
Add new validation rule and updated text.  Need to make sure UML is updated.
