### ISSUE TITLE
Best practices on interaction types and participant roles

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#34]
It would be useful to have more documentation about which interaction types and participant roles go together.  While it would be nice to have ontology support to check this, at a minimum, we need to document it.

**Comment by jakebeal** [comment]
We need to make a table!

**Comment by cjmyers** [comment]
Added new validation rule 11907.

**Comment by cjmyers** [comment]
Updated tables 11 and 12.  Still requires prose updates around tables.
