### ISSUE TITLE
ordering of serialized elements

### ISSUE THREAD

**Issue by chrismacklin** [SynBioDex/SBOL-specification#37]
The SBOL2 specification has no explicit comments about whether or not sibling nodes in the serialized object tree must have a particular ordering by type.  The examples are also inconsistent on this.  Most of the serialization examples follow the ordering of the serialization template, but some do not.  For example, a SequenceAnnotation object specifies the following template:
```xml
<sbol:SequenceAnnotation rdf:about="...">
    ... properties inherited from identified ...
    zero or one <sbol:component rdf:resource="..."/> element
    one or more <sbol:location><sbol:A_LOCATION_SUBCLASS rdf:about="...">...</sbol:A_LOCATION_SUBCLASS?</sbol:location> elements
</sbol:SequenceAnnotation>
```
where all components appear before all locations.  However, in the example that immediately follows, their order is reversed:
```xml
<sbol:SequenceAnnotation rdf:about="http://partsregistry.org/cd/BBa_F2620/anno2"> 
...
    <sbol:location>
        <sbol:Range rdf:about="http://partsregistry.org/cd/BBa_F2620/anno2/range"> 
        ...
        </sbol:Range>
    </sbol:location>
    <sbol:component rdf:resource="http://partsregistry.org/cd/BBa_F2620/rbs"/>
</sbol:SequenceAnnotation>
```

Does the spec care about ordering of sibling-level nodes?  One way or the other, the spec should be amended to be clear on this (and clean up the errors in the examples if ordering is considered).

**Comment by cjmyers** [comment]
The order of child objects is indeed arbitrary.  I thought we had spelled that out in the specification, I certainly remember this issue discussed.  However, if it is missing, it should certainly be added and/or better highlighted.

Chris

**Comment by bbartley** [comment]
Order of child objects should be represented by custom annotations.  We should check the specification to be explicit that there is no semantic ordering in serialization.  However, individual libraries can implement this, so this can be raised as a libSBOLj issue, for example.
