### ISSUE TITLE
Should SBOL recommend an encoding scheme?

### ISSUE THREAD

**Issue by udp** [SynBioDex/SBOL-specification#372]
Although we do not mandate any specific serialization for SBOL, should we recommend that where possible Unicode should be used as the encoding scheme?

**Comment by jakebeal** [comment]
How do RDF libraries handle this in general?  If the encoding is not unicode, will and RDF library be smart enough to handle the unicode characters?

**Comment by cjmyers** [comment]
Libraries handle this, so we will leave this out.  @udp please reopen if you object.
