### ISSUE TITLE
Explain 'hasProperty' vs. 'property' in Conventions

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#374]
I don't think I understand what the distinction is between when we use the `hasProperty` naming convention versus using the `property` naming conventions.   We do not currently explain in the Conventions section of the specification, and it seems to me that we may not be consistent in how we are applying it.

I have three theories:

1. *`hasProperty` is for child objects, `property` is for TopLevel objects.*  Contradicted by `hasSequence` and `hasModel` on `Component`.
2. *`hasProperty` is for child objects, `property` is for referenced objects.* Contradicted by `hasSequence` and `hasModel` on `Component`.
3. *`hasProperty` is for pointers to to class `Property`, `property` is for pointers to objects with a different class.*  This one seems to be consistent.

Can somebody please confirm if this is correct, and then we can add it to the Conventions section?

**Comment by cjmyers** [comment]
Yes, I agree that (3) is my understanding too.
