### ISSUE TITLE
Change strong required to weak required for validation rule sbol-11703.

### ISSUE THREAD

**Issue by zgzn** [SynBioDex/SBOL-specification#38]
Rule sbol-11703 should be a weak required (triangle), not a strong required (check-box), just like rule sbol-10604.

**Comment by bbartley** [comment]
This change is essentially correcting an error in the spec, and making sbol-11703 consistent with other validation rules.

**Comment by goksel** [comment]
Should they both be strongly required instead (rather than making them both weakly required)?

**Comment by cjmyers** [comment]
Changed to new partial check category.
