### ISSUE TITLE
Provenance ontology namespace should be changed

### ISSUE THREAD

**Issue by goksel** [SynBioDex/SBOL-specification#380]
The PROV-O documentation states the PROV-O namespace as "http://www.w3.org/ns/prov#". However, the SBOL spec uses the "https://www.w3.org/TR/prov-o/" namespace. I think we should be using the previous link.

Examples:
https://www.w3.org/TR/prov-o/Agent --> Not resolvable
http://www.w3.org/ns/prov#Agent --> resolvable via the PROV-O ontology
https://www.w3.org/TR/prov-o/#Agent --> Resolves to the related HTML section, since "https://www.w3.org/TR/prov-o/" is used for web access only.

**Comment by lmnh** [comment]
closes #380
