### ISSUE TITLE
Some of the Measurement related property names should be corrected 

### ISSUE THREAD

**Issue by goksel** [SynBioDex/SBOL-specification#390]
The following changes should be made to be consistent with the Ontology of Units of Measure:
- om:alternativeSymbols [0..*] --> om:alternativeSymbol [0..*]
- om:label[1] --> rdfs:label[1]
- om:alternativeLabels [0..*] --> om:alternativeLabel [0..*]
- om:comment[1] --> rdfs:comment[1]

rdfs points to "http://www.w3.org/2000/01/rdf-schema#"

**Comment by IsabelMarleen** [comment]
Pull request #407 solves this issue
