### ISSUE TITLE
SBOL RDF serialisation example (section 8) should be fixed

### ISSUE THREAD

**Issue by goksel** [SynBioDex/SBOL-specification#392]
The entities in the RDF example start with "#" and the base URL ends with #, causing the double use of the # character. The following example may work:
@prefix sbol: <http://sbols.org/v3#> .
@base <http://example.com#> .
@prefix :  <http://example.com#> .

:pLac a sbol:Component ;
sbol:name "pLac" ;
sbol:description "lactose inducible promoter" ;
sbol:sequence :sequence .

:sequence a sbol:Sequence ;
sbol:encoding <http://www.chem.qmul.ac.uk/iubmb/misc/naseq.html> ;
sbol:elements "caatacgcaaaccgcctctccccgcgc" .

**Comment by goksel** [comment]
In addition, the encoding property value should come from Table 1 in the spec.

**Comment by chofski** [comment]
I've made this update as recommended (see PR #406 , but the current approach for highlighted syntax could be rethought. Maybe there is a LaTeX package to enable this?
