### ISSUE TITLE
Best practices for creation and modification dates

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#4]
What are the best practices for annotating with creation and modification dates?
Should they be annotations, or are needs well enough understood to pull into the core specification?
Is this needed at all?

**Comment by goksel** [comment]
DC terms should be advised to specify creation and modification dates. In the future, if we decide to incorporate these properties into the spec, we will be backward compatible too. More explicitly:
http://purl.org/dc/terms/created:To annotate SBOL entities with the creation date
http://purl.org/dc/terms/modified: To annotate SBOL entities with the modification date

DC terms namespace to be declared in the SBOL documents: http://purl.org/dc/terms/
DC terms prefix to be declared in the SBOL documents: dcterms

Creation and Modification dates would then be serialized with the "dcterms:created" and "dcterms:modified" properties respectively.
