### ISSUE TITLE
Need validation rule that there should only be one SBOL namespace

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#40]
Each SBOL document should only include one SBOL namespace for a particular version.  In other words, multiple versions should not be allowed in the same file.

**Comment by cjmyers** [comment]
And exactly one namespace should be present.

**Comment by graik** [comment]
This needs to be carefully checked with people working on the RDF level. From what I can tell, there is plenty of situation where one may want to mix objects belonging to different name spaces (e.g. with different base URIs) in a single SBOL document.

**Comment by cjmyers** [comment]
This is not an object level namespace but rather the document level one. We changed serialization so drastically when we moved to SBOL 2 that it would be very difficult to parse both at the same time. Namely we got rid of the odd inlining from SBOL 1 that was ugly and error prone.

We should not though have any problem with mixing different versions of SBOL 2 so I guess the rule should be more simply that SBOL 1 and 2.x cannot be in same file.

Chris

**Comment by bbartley** [comment]
This will be dealt with as a Best Practice.  The Best Practice is:
XML serializations should contain only one version of SBOL.  If multiple versions are present, libraries will default to interpreting the latest version of SBOL.  All other elements in an SBOL namespace will be treated as Custom Annotations

**Comment by cjmyers** [comment]
Text added to section 12.1.
