### ISSUE TITLE
Add more requirement to sbol-10207 to allow it to be checked.

### ISSUE THREAD

**Issue by zgzn** [SynBioDex/SBOL-specification#43]
We should also require an object to have a newer version than that of the wasDerivedFrom.

**Comment by cjmyers** [comment]
I think this is handled in sbol-10211.

**Comment by bbartley** [comment]
This validation rule is a guideline to the user that is not machine-checkable.  We will move this to a 4th category of validation rule for non-machine readable rules as prescribed under issue 48.
