### ISSUE TITLE
Abstract class names are not italicized

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/SBOL-specification#431]
The last two sentences in Section 4.2 say that abstract classes have italicized names:
> Some classes in the SBOL data model cannot be instantiated as objects and exist only to group common properties for inheritance. These classes have italicized names and are known as abstract classes.

The first sentence in section 6.1 says that Identified is an abstract class. Section 6.2 opens with the statement that "TopLevel is an abstract class..." Neither of these classes are italicized in their respective UML diagrams (Figures 5 and 6 respectively).

These two appear to be the only classes that are abstract. For instance, Feature is not indicated to be abstract. If Identified and TopLevel are the only two abstract classes, it would be clearer to state that in the abstract class discussion in Section 4.2 rather than leaving a reader to hunt for these in the body of the specification.

**Comment by jakebeal** [comment]
Looks like we aren't consistent in marking TopLevel and Identified also.

I believe that the full set of abstract classes at present are:

- Identified
- TopLevel
- Feature
- Location

**Comment by tcmitchell** [comment]
While `Identified` and `TopLevel` are indicated as abstract in the text, neither `Feature` nor `Location` have an indication that they are abstract. None of these classes are italicized in any place that I see.

**Comment by jakebeal** [comment]
Looks like this is actually a problem related to umlet exports, as in most cases the source is italicized, but the italics are lost on export.

**Comment by jakebeal** [comment]
This is an issue that cannot be reasonably resolved with the umlet tool on MacOS; apparently, this is a known bug that has not been fixed for 4 years, and the recommended workaround is to embed the font in each diagram, which seems wasteful.
https://github.com/umlet/umlet/issues/471

Can somebody with a non-Mac OS try doing an export and see if you can preserve the italics?

**Comment by jakebeal** [comment]
(alternately, we could stop using italics to mark abstract classes)

**Comment by jakebeal** [comment]
I've marked Feature and Location as abstract in the prose with pull #449. Still can't resolve the italics issue for now.

**Comment by jakebeal** [comment]
Given the tooling issue, I'd like to suggest that we just do away with the italics as a marker. @tcmitchell , @cjmyers : any objection or alternate suggestion?

**Comment by cjmyers** [comment]
Fine by me
