### ISSUE TITLE
Primary published version of 3.0.1 should not use redlines

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#441]
While our typical practice is to use redlines to identify specification changes, I believe that doing so for the SBOL 3.0.1 specification vs. the 3.0.0 specification will be more confusing than valuable. 

Version 3.0.1 is the first "real" implemented version, and there are substantial differences with 3.0.0. The differences between 3.0.0 and 3.0.1, however, will only really be of interest to the very small community of alpha implementers who have been involved in the development of 3.0.1. Most people who encounter the SBOL 3 specification, however, will be more confused than enlightened by a description of our non-backward-compatible bug fixes in the 3.0.0 spec.

Thus, I would suggest that, even if we produce a redline version, it should not be the primary published version.

**Comment by cjmyers** [comment]
Redline version still use to save time during final review before "publication".

**Comment by jakebeal** [comment]
I'm fine with that, though I may suggest some areas be done as blocks rather than interlaced.

**Comment by cjmyers** [comment]
That's fine.

**Comment by jakebeal** [comment]
Accordingly, I propose that we just use redline generating LaTeX tools on the final .tex files rather than tracking it all through the document by hand. There's a lot of it, and I'm finding it very confusing at times.

**Comment by cjmyers** [comment]
Ok sounds good

**Comment by jakebeal** [comment]
I'd like to leave this open until the modifications are committed to the repo.
