### ISSUE TITLE
Change orientation to SO URIs?

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#455]
There was a TODO note lingering in the specification that observed that we have coined our own orientation URIs when we could be using the orientation URIs from Sequence Ontology:

> Should we swap these custom orientation types to use the  SO direction attribute instead? http://www.sequenceontology.org/browser/current_release/term/SO:0001029

It has been a best practice for us to re-use existing materials wherever possible. Can we do that in this case as well?

**Comment by cjmyers** [comment]
These seems like a good idea to me.

**Comment by jakebeal** [comment]
Somebody needs to make sure this has actually gotten into the spec via a pull request.
