### ISSUE TITLE
Rule 10806 can be more specific

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#46]
It says that remote of mapsTo must point to a ComponentInstance but it is actually a FunctionalComponent within the referred to ModuleDefinition.  It should be similar to 10804.

**Comment by cjmyers** [comment]
I think actually 10808 handles this.

**Comment by bbartley** [comment]
Remove this rule, it's redundant with 10808.

**Comment by cjmyers** [comment]
Removed 10806.
