### ISSUE TITLE
Italics for abstract classes in UML diagrams

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/SBOL-specification#469]
The convention for UML class diagrams is to use italics for abstract Classes, such as `Identified` and `TopLevel`.  The current diagrams in the spec document do not appear to follow this convention.

**Comment by bbartley** [comment]
Sorry, in some cases, we do in fact use this convention, but it's not consistently applied.  For example, Fig. 9 and 10 do not adhere to this convention.

**Comment by jakebeal** [comment]
I think this was already resolved in favor of stopping the convention, and is just not in the release: https://github.com/SynBioDex/SBOL-specification/issues/431

**Comment by bbartley** [comment]
OK, I thought I had remembered seeing something about this previously, but couldn't find it when I searched the issues.
