### ISSUE TITLE
Mention Maven semantic versioning in rule 10211

### ISSUE THREAD

**Issue by zgzn** [SynBioDex/SBOL-specification#47]
Determination of versions in this rule needs to mention the use of Maven semantic version scheme.

**Comment by bbartley** [comment]
10211 will become a human-checkable rule only, 10207 will add language that if you follow 10207 then 10211 becomes machine-checkable

**Comment by cjmyers** [comment]
Added language about versioning and wasDerivedFrom field implications to 10207.

**Comment by jakebeal** [comment]
This has now been moved to 10302.
