### ISSUE TITLE
URI (and namespace) equality

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#476]
I ran into problems with namespace URIs in #SynBioDex/pySBOL3/issues/343 , because I was comparing them with string equality rather than URI equality. 

To help keep other people from running into this problem, I would propose adding the following clarifying text to the specification in Section 5.1:

> Because identities are URIs, both URIs and URI prefixes MUST be compared under the rules for URI equality. This means, for example, that namespaces `https://synbiohub.org/`, `https://synbiohub.org`, and `https://synbiohub.org:443/` are all equal.

**Comment by cjmyers** [comment]
This is not true, need to revert the change to the spec

**Comment by goksel** [comment]
Java treats the following URLs differently, and the prints false both comparisons.
        URI a=URI.create("http://abc.org");
        URI b=URI.create("http://abc.org/");
        URI c=URI.create("http://abc.org:443");
        
        System.out.print(a.equals(b));
        System.out.print(a.equals(c));

**Comment by cjmyers** [comment]
Need to revert #481
