### ISSUE TITLE
Make a new category for weak required rules that are impossible to check

### ISSUE THREAD

**Issue by zgzn** [SynBioDex/SBOL-specification#48]
For the following weak required rules, they are not machine checkable. It would be nice to put them in a separate category, since other weak required rules are at least partially checkable. 
10404, 10504, 10506, 10508, 10509, 10514, 10515, 11408, 11503, 11505, 11603, 11903, 11904, 12005

**Comment by jakebeal** [comment]
Consensus: yes, we should do this.
