### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#487]
Dear SBOL editors,

My name is Johan Guillen, I am trying to learn SBOL. I am reading the SBOL specification document and I think it is great.

I think I found a few typos, for if that would be helpful:
-Page 7 line 17: "organsiations"
-Page 4 line 18: missing word "to", between "can be used" and "represent biological processes"
-Page 11 line 30: word "roles" is referenced two times, I think second one should be "roles"
-Page 14 line 16: I think this line should be eliminated
-Page 61 line 13: "quantitive"

My apologies beforehand, I am not an expert in the English language.

Thank you.

Best wishes,
Johan Guillen

**Comment by LukasBuecherl** [comment]
See PR #490
