### ISSUE TITLE
Typo in Section 10.1

### ISSUE THREAD

**Issue by hgscott** [SynBioDex/SBOL-specification#505]
I found a minor typo in section 10.1. The first, second, and sixth bullet points (lines 16, 17 & 22) all use the term `Compenent Definition`, rather than "Component".  

https://github.com/SynBioDex/SBOL-specification/blob/555e69f053418623ada7d0c20a4f9fc6bbbf480e/mapping.tex#L16-L22

**Comment by tcmitchell** [comment]
Thanks for letting us know!
