### ISSUE TITLE
Update jib_abstract_3.0.0 with jib_abstract_3.0.0

### ISSUE THREAD

**Issue by LukasBuecherl** [SynBioDex/SBOL-specification#509]
The abstract needs to be replaced with the current version 3.1.0 in the repo to avoid confusion. The abstract 3.1.0 can be found in the overleaf project shared with the editors.

**Comment by Gonza10V** [comment]
Just to have this right, its Update jib_abstract_3_0.tex with jib_abstract_3_1.tex

**Comment by cjmyers** [comment]
Yes
