### ISSUE TITLE
Quick grammar fixes

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOL-specification#51]
Page 4: line 6
 do mean that **an **SBOL 1.x ﬁle is not a valid SBOL 2.0 ﬁle

Page 11: line 13 
 Because the same deﬁnition** might appear** in multiple designs or 

Page 24: line 12
 As shown below, each of these objects and URIs **are **serialized as part of an implicit set 

Page 24: line 13 + 14
 In particular, each objectis serialized as **an **RDF/XML 13 node nested within a property, while each URI (except the identity) is serialized as **an** rdf:resource on a property.

**Comment by mehersam** [comment]
The above fixes have been changed.

**Comment by mehersam** [comment]
Done.
