### ISSUE TITLE
SBOL 2 needs clear semantics to distinguish whether certain classes / properties indicate a designer's intent versus an empirical observation after the design is actualized into a real biological construct

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/SBOL-specification#53]
For example, a ComponentDefinition.role property might be used in design automation to indicate the designer's intent for that component.  However, a ComponentDefinition.role property might also be used in a quality control pipeline to indicate a biological observation or annotation about how that component actually behaves in a given context.  So far, this problem has received little attention because the community has been focused on supporting biodesign, the starting point for synbio workflows.  However, in later stages of workflows, after a design is actualized, biological description becomes necessary.   SBOL should make a clear semantic distinction between biological design and biological description.

**Comment by jakebeal** [comment]
This is an area of active research and needs to have use cases worked out before we can determine how much, if any, changes need to be made to the specification.

**Comment by bbartley** [comment]
Resolved by SEP#17 and adoption of the Implementation class.
