### ISSUE TITLE
displayId should be renamed

### ISSUE THREAD

**Issue by 3ach** [SynBioDex/SBOL-specification#54]
As we are hacking through the SBOL Visual spec, we realized that displayId is a bit of a misleading name and should be renamed for clarity to simply id. On a diagram, the name is the value that is more likely to be displayed.

**Comment by mikebissell** [comment]
Be careful. 'id' normally conveys a uniqueness requirement.

How about 'label'?

**Comment by drdozer** [comment]
It is closest to http://purl.org/dc/elements/1.1/identifier

On 16 March 2016 at 15:38, mikebissell <notifications@github.com> wrote:

> Be careful. 'id' normally conveys a uniqueness requirement.
>
> How about 'label'?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SynBioDex/SBOL-specification/issues/54#issuecomment-197387384>
>



-- 
Dr Matthew Pocock
Turing ate my hamster LTD
mailto: turingatemyhamster@gmail.com

Integrative Bioinformatics Group, School of Computing Science, Newcastle
University
mailto: matthew.pocock@ncl.ac.uk

gchat: turingatemyhamster@gmail.com
msn: matthew_pocock@yahoo.co.uk
irc.freenode.net: drdozer
skype: matthew.pocock
tel: (0191) 2566550
mob: +447535664143

**Comment by jakebeal** [comment]
I have marked this as version 3 because, no matter how good an idea this is, changing a core name like this will render many things obsolete.

**Comment by graik** [comment]
Historic context: We closely looked at the partsregistry.org / Biobrick data sheets when coming up with these fields. So let's look at this example: http://parts.igem.org/Part:BBa_E0040
* displayID ... BBa_E0040
= human-readable ID to find this exact record within the provider's database/website

* name ... GFPmut3b
= gene name or similar "human-understandable" name, usually following some expert convention

The term "displayID" was supposed to transmit the idea that the ID should be useful (displayed to) for human beings to quickly locate a part and to communicate about it. We had a vocal minority arguing instead for sequence-compiled hash values or for long and cryptic globally-unique IDs (the same discussion has popped up several times). By choosing "displayID" as a term, we wanted to clarify that this was *not* really desired (although not forbidden).

Looking forward to the SEP.

**Comment by graik** [comment]
+1 to Matt's "identifier" and they way it is defined. That's exactly what displayID was supposed to be.

**Comment by jakebeal** [comment]
We seem to have kept the name "displayId" in SBOL 3.  Last chance for a change is _now_ as SBOL 3.0.1 works its way through implementation.

**Comment by cjmyers** [comment]
We discussed this at HARMONY and decided we could not come up with a better name, so I suggest closing.
