### ISSUE TITLE
wasDerivedFrom checks only for TopLevel

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#56]
The purpose of the wasDerivedFrom property is to connect different versions of SBOL data objects.  For example, when you create a copy of a TopLevel object with a new version, the wasDerivedFrom field is set from the identity of the original object.  Since new versions of child objects cannot be created independent of new versions of TopLevel objects, the wasDerivedFrom field only really applies to TopLevel objects.  

There are three things currently being validated for wasDerivedFrom objects:
1) The wasDerivedFrom field should be a URI (sbol-10208).
2) An object should have a later version than the object it is derived from (sbol-10207/sbol-10211).
3) The wasDerivedFrom field should not form a circular reference chain (sbol-10209/sbol-10210).

The later two checks are currently only being checked for TopLevel objects, and as I argued above this field is only really meaningful for TopLevel objects.  Therefore, I would like to move these four validation rules into the TopLevel section.  Doing so would not change the validity of any files, since it loosens the rules and the tighter rules are not being checked anyway.  So, I would argue that making this change is a 2.0.1 change, and it would put the specification more inline with the implementation.

An argument could also be made to move the last rule and the wasDerivedFrom field itself to the TopLevel class.  Doing this would not actually change the validity of files, since the wasDerivedFrom field would simply turn into an annotation for any non-TopLevel object.  Therefore, it could be argued that this change would also be okay for 2.0.1.  However, it would change the UML diagrams to move the field from Identified to TopLevel.  Therefore, I could also imagine this as a 2.1 or 2.2 change.

**Comment by jakebeal** [comment]
The editors believe that wasDerivedFrom is currently poorly specified in its semantics.  Newcastle is working on an improvement for discussion of provenance, but that will be an SEP change, and we should not delay library development while waiting for it.

We do, however, believe that in the current state of ill-definition, it is appropriate to weaken the rules about "later version" and circularity to apply only to TopLevel, where their meaning is clear.  They might be changed again later, but in the mean time this should not cause any disruption and will allow libraries to completely implement.  We thus judge this aspect to be non-SEP and request that you implement it and send a pull request.

Any desire to move the field should be forked into a new SEP issue.

**Comment by cjmyers** [comment]
Ok, I’ve moved 10207, 10209, 10210, and 10211 to TopLevel.  Rule 10208 must stay right now in Identified, since wasDerivedFrom field has stayed in Identified, for now.

**Comment by cjmyers** [comment]
Done.
