### ISSUE TITLE
Revise rule 10511

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#57]
Proposed new language:

"The roles property of a ComponentDefinition SHOULD only contain a URI from the sequence feature branch of SO, if it includes the DNA or RNA type, as listed in Table 2, in its set of types.”

**Comment by cjmyers** [comment]
Add this text to draft.

**Comment by jakebeal** [comment]
Can you please explain and give the diff?

**Comment by cjmyers** [comment]
Here is original:
The roles property of a ComponentDefinition SHOULD only contain a URI provided in 29 Table 3 if one of its types is cross-listed with this URI. 30 Reference: Section 7.7 on page 21

Basically, the table was only a subset of SO, but now that we can easily check over all SO, we refined the language to essentially make it clear that SO should be used for DNA/RNA types.

**Comment by jakebeal** [comment]
I am having a difficulty with the meaning of "only" in this case (and also the original).  Do you mean that no non-SO roles should be used, or that SO roles should not be used for other things, or something else?  I think this should be clarified, changing "only" to a clearer conditional.

**Comment by cjmyers** [comment]
Agree confusing.  Only means to ONLY use SO terms for DNA and RNA types.  Moved the only, is it better?

**Comment by jakebeal** [comment]
Please rephrase without the word "only"

**Comment by cjmyers** [comment]
Hmm, that would change the meaning.  

If I drop “only”, then it says that you should use SO for DNA/RNA (which is the point of 10527).  However, the point here is that SO should not be used in the case where it is not RNA/DNA type.

**Comment by jakebeal** [comment]
I mean there are ways that you can say your intent using different English words that are not as ambiguous as "only", whose meaning changes depending on where you put it in a sentence.

**Comment by cjmyers** [comment]
Hmm, I’ve tried a few different ways to rephrase but I keep trying to add the word only.  If you understand my meaning, would you mind trying to rephrase?  

Thanks.
