### ISSUE TITLE
New rule 10527

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#58]
Exactly one \sbol{URI} contained by the \sbolmult{types:CD}{roles} property of a \sbol{ComponentDefinition} SHOULD refer to a term from the sequence feature branch of SO, if it includes the DNA type, as listed in \ref{tbl:componentdefinition_types}, in its set of \sbolmult{types:CD}{types}.

Does this look okay?  Should it also include RNA type?

**Comment by cjmyers** [comment]
Added RNA type to this rule.

**Comment by jakebeal** [comment]
Can you please explain and give the diff?

**Comment by cjmyers** [comment]
This is actually a new rule.  It is the reverse of 10511.  Where 10511 says SO should only be used for DNA/RNA types, this rule states that SO should be used for DNA/RNA types.

10511 fails when a CD has a SO role but is not DNA/RNA type
10527 fails when a CD has DNA/RNA type but does not have exactly one SO role

**Comment by jakebeal** [comment]
I think this may not be a valid rule.  Here are two cases that I believe would appropriately violate it:
1. A CD has a DNA/RNA type but its role is poorly understood and thus left unspecified.
2. A CD legitimately plays more than one rules.

**Comment by cjmyers** [comment]
One thing to keep in mind is that this is a best practice.  So, it is used to catch common errors, but it okay to violate the rule when there is a need.  A missing role or something that plays multiple roles I would think is an exception rather than the norm.  Normally, when there is no role or multiple roles, you would like I think a warning to check this case.

Also, if you really do not know, it would seem reasonable to have an SO term for unknown role.  For the second case, do you have an example?  The examples that Brian and I worked through were all using a general term and a specific term.  For example, you could say something is a promoter and more specifically a constitutive promoter.  This, in my opinion, defeats the purpose of using an ontology, since it makes more sense to say it is a constitutive promoter and infer that it is a promoter.

If the two roles do not have a descendent relationship, then there is a good chance these roles are conflicting and this is a bug.  This is the only way we have right now of catching conflicting roles.  

Even if you can find a good example where there would be two roles on different branches, if this is a special case, I would still argue on keeping this best practice rule. We have many best practice rules that would not survive otherwise.  The reason a rule is a best practice and not required is we suspect that sometimes there may be a good reason to violate it, but most violations will actually be typos or errors in the data.
