### ISSUE TITLE
refer to W3C recommendation for "cool URIs" in RDF

### ISSUE THREAD

**Issue by graik** [SynBioDex/SBOL-specification#63]
The following document describes the W3C recommendation on how URIs are to be minted for real-world objects described in RDF documents:

https://www.w3.org/TR/cooluris/

This document should be referred to as a best-practice in the specification.

The W3C describes two recommended strategies:

1) low-tech "Hash URIs" such as http://www.example.com/dnaparts/about#part1
2) an URI giving a 303 response allowing content negotiation between web server and client

Case 1 is recommended for small collections of items. It is simple but has the disadvantage that each request triggers the transfer of the _whole_ collection contained in the RDF document. 

Case 2 is recommended for larger collections and is more flexible in that it allows to serve information about a certain "Thing" in different formats.

**Comment by cjmyers** [comment]
No longer relevant for SBOL3 which has new URI rules.
