### ISSUE TITLE
Which ontology should be used for protein roles?

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#7]
Currently, ontologies are recommended for DNA, RNA, and small molecule roles.
No ontology is recommended for proteins.
GO and UniProt have been suggested.  Is one of them actually appropriate?

**Comment by jakebeal** [comment]
Needs an SEP because we need to explain clearly why we choose the thing that we use.

**Comment by jakebeal** [comment]
UniProt may have license issues regarding commericial use that prevent it from being an open standard. They require CC-NoDerivs, see: http://www.uniprot.org/help/license

**Comment by graik** [comment]
http://www.ebi.ac.uk/GOA should be looked at

**Comment by jakebeal** [comment]
In SBOL3, UniProt is recommended, which I believe resolves this question.

**Comment by cjmyers** [comment]
Ok, closing.
