### ISSUE TITLE
Sequence annotation cannot have both a role and a component

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#70]
We would like to avoid backward compatibility issues when SEP010 (or something of its sort) is adopted, but also want to get SBOL 2.1 out including the new roles from SEP004.  Thus, we plan to do the following:

Rather than keeping roleIntegration on SequenceAnnotation, we can add a constraint that says a SequenceAnnotation cannot have both a role and a component.  This will prevent the need for roleIntegration in SequenceAnnotation, and can readily be enforced because both SequenceAnnotation and Component are child objects of ComponentDefinition, meaning they generally travel together.

I have marked this as both "Needs SEP" and "Non-SEP" for the following reasons:
1. The formal vote on data model effects will come as part of accepting SEP010, in whatever form it ultimately assumes.
2. The was a general consensus on SEP010 (or something like it) in the discussions at COMBINE
3. All of the key stakeholders are agreeing with the general path forward
4. Even if SEP010 completely fails and the consensus changes back toward roleIntegration in SequenceAnnotation, dropping the constraint and adding roleIntegration is a backward compatible change that could be implemented in SBOL 2.2.

**Comment by cjmyers** [comment]
Included in the new pull request.

**Comment by jakebeal** [comment]
This has been integrated into the spec.
