### ISSUE TITLE
Sequence by reference

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#83]
[also posted on sbol-dev]

In light of the recent discussion of encoding whole organism genomes in SBOL, I have been thinking about the pragmatics related to providing sequence information. In particular, I would note the following three key facts:
1. Actually listing out the entire sequence for a large replicon (e.g., an entire chromosome) is a lot of information and often not of primary interest in design.
2. We still want to be able to precisely link large sequences to designs (e.g., noting where a construct is inserted into a replicon)
3. There are already lots of good persistent databases out there hosting sequence information.  For example, the sequence of E. coli MG1655 is hosted by the NCBI at https://www.ncbi.nlm.nih.gov/nuccore/NC_000913

As such, I propose that we allow an alternative representation of sequence content by means of a link to an external database. This is a very semantic-web / federated database way of doing things, and I see two reasonable proposals for how to do it:

A) Allow ComponentDefinition.sequence URIs to point to non-SBOL objects (i.e., expand rule sbol-10513)
B) Add a new property to Sequence, called something like "reference", which can point to a non-SBOL object as an alternative to listing the sequence explicitly in the "elements" field, then require that at least one of the two be defined (i.e., expand rule sbol-10402) and require that if both are defined that they are consistent.

Of these two options, I think that B (adding "Sequence.reference") is preferable, for two reasons:
1. It follows our precedent, established as for Model, of referring to external resources through wrapper objects
2. It allows the potential for information to assist in integrating the external sequence information to be added later.

**Comment by graik** [comment]
Good proposal! I would also very much prefer a new reference field for this
purpose. (Option 2)
Greetings
Raik

**Comment by jakebeal** [comment]
Address in SBOL 3 via the ExternallyDefined class adopted in [SEP 036](https://github.com/SynBioDex/SEPs/issues/81)
