### ISSUE TITLE
Vertical Orientation Option

### ISSUE THREAD

**Issue by jfarlow** [SynBioDex/SBOL-specification#86]
Is there a standard for vertical orientation of the SBOL visual language?

It seems like a visual language should be compatible with the vertical scrolling patterns commonly used on a computer screen.  With more than just a few components it becomes impossible to annotate a SBOL map without having a user either scroll horizontally (a terrible user interface pattern), or have 'rows' which must be kept track of and would be both jarring to the user, and difficult to implement in a responsive way.

Has there been any thought to how the visual language can be adopted in a vertical manner so that theoretically a massively annotated plasmid, or even small chromosome could be reasonably represented on a computer screen?

**Comment by cjmyers** [comment]
Hi,

I suggest forwarding your question to the SBOL-Visual mailing list (sbol-visual@googlegroups.com).  If you are not yet a member, you can subscribe by emailing the SBOL Editors (sbol-editors@googlegroups.com).

Thanks for your input.

Chris

**Comment by cjmyers** [comment]
Moved to SBOL Visual Tracker
