### ISSUE TITLE
Need a validation rule for namespace to end with delimiter

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#88]
Namespaces that do not end with a delimiter (/, #, :) cause problems with RDF tooling.  There should be a new validation rule (best practice?) that indicates that namespaces MUST (SHOULD?) end with a delimiter.

**Comment by jakebeal** [comment]
This is a non-SEP change; please socialize on the list, then create a patch and pull request.

**Comment by graik** [comment]
The basic rule should be that everything written by SBOL tools needs to be RDF compatible.

**Comment by graik** [comment]
Could we not simply demand that all SBOL documents pass a RDF syntax validation? This should solve this and many other potential issues, shouldn't it?

**Comment by cjmyers** [comment]
As far as I know, it is not technically illegal XML or even I believe illegal RDF/XML, which is I believe how this problem got through to this point.
