### ISSUE TITLE
Best practice needed to add extra rdf:type to distinguish GenericTopLevels

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#89]
In RDF stores, GenericTopLevels and nested Annotations cannot be distinguished.  To address this, there needs to be an extra rdf:type to indicate when an object should be treated like a GenericTopLevel, such as:

    <pr:DataSheet rdf:about="http://partsregistry.org/cd/BBa_J23119/Data">
    <rdf:type rdf:resource="http://sbols.org/v2#GenericTopLevel"/>

**Comment by jakebeal** [comment]
This marking is based on the possibility that this might be addressed by a best practice. It might change to SBOL 2.2 if it actually needs a data model enhancement.

**Comment by jakebeal** [comment]
@cjmyers Does this still need to be addressed for SBOL3?

**Comment by cjmyers** [comment]
No, since in SBOL3 there is no difference between nested annotations and generic top levels.  They are simply alternative renderings.
