### ISSUE TITLE
Add examples of use of each class

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#9]
Put a small concrete example diagram for each toplevel class, in the style of the mapsTo diagram

[imported from LaTeX]

**Comment by cjmyers** [comment]
@jakebeal do we still want to add this to the specification?

**Comment by jakebeal** [comment]
I think I'm not in favor of adding this to the core specification document, since some of the examples can get pretty complex.  I'm strongly in favor of making the example collection we've talked about alongside the specification, however.
