### ISSUE TITLE
Problem with URIs in Example B.1.7

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#92]
This example uses an annotation with problematic URIs.  The experience URI references the information URI.  This does not make any sense.  The experience reference is okay because it is pointing to an external source, but the URI for information should be a URI local to the document.  Perhaps: http://partsregistry.org/cd/BBa_J23119/information.  Also, having "?" and "=" in a URI for an internal object is not ideal for RDF stores.

**Comment by jakebeal** [comment]
Please create a patch and pull-request.
