### ISSUE TITLE
Authors field for ComponentDefinitions (and other things?)

### ISSUE THREAD

**Issue by graik** [SynBioDex/SBOL-specification#95]
Issue first raised by Maxwell Bates on sboldev. Attribution obviously is important and newly designed biological parts should have one or multiple authors. 

There are different RDF terminologies for this. Which ones to use and where to put them should be spelled out in the spec and supported by all libraries.

**Comment by cjmyers** [comment]
Dublin Core seems to meet the needs.  If so, should add a best practice section explaining how to use it.
