### ISSUE TITLE
displayId is not meaningfully optional

### ISSUE THREAD

**Issue by chrismacklin** [SynBioDex/SBOL-specification#96]
Although displayId is listed in the spec as OPTIONAL, it is REQUIRED for a SBOL object to be "compliant".  It is, if anything, extremely misleading for this field to be OPTIONAL, as omitting it will make the Identified object be incompatible with essentially all of the core tooling.

What was the motivation for distinguishing a "compliant" SBOL document from one which adheres to the specification?  What is the intended purpose for the specification to state that a field is OPTIONAL when, for an object to be "compliant", it must be present?  What is the use case for a non-compliant document?

**Comment by jakebeal** [comment]
The library authors can correct me if need by, but my understanding is that the optionality of this field is intended to make it easier to import external resources that were not created with SBOL in mind and might not have a clear or meaningful displayId.

**Comment by chrismacklin** [comment]
Yet, one could not use such SBOL-converted resources with, say SBOL Designer.

The implication here is that there are three tiers of sbol compliance:

- objects which do not adhere to the specification
- objects which adhere to the specification
- objects which are "compliant" and meet a higher standard

This implies some confusing terminology.  An object which adheres to the entire specification is "noncompliant", yet, of course, objects which do not adhere to the specification are also reasonably referred to as "noncompliant".  This three-tier system is not very well documented; one could read the entirety of Section 7 of the spec, write an implementation of it that adheres to the spec to the letter, and yet the resulting documents would be rejected by the core tooling.  Nowhere in Section 7 does it mention that omitting fields that are specified as OPTIONAL would imply this result.

Why have these three tiers of compliance at all?

**Comment by cjmyers** [comment]
It was a compromise position which as with all compromises is not ideal for either side.  URIs have created a lot discussion and debate.  Namely, how do we ensure they are unique while still making them meaningful.  The idea of a compliant URI was born from this debate.  However, it was considered by others that we could not require any restrictions on the URIs.  So, to move forward, we agreed to making it recommended but not required.  

In addition to compliance, there are also other best practice rules that also come into play with similar arguments.  In SBOL community, we have tried to be very flexible to let people do whatever they want, but the cost of this is it is difficult to make tools understand each other with all this flexibility.  Therefore, various best practice rules are put into place to say, if you follow these you are going to increase your level of exchange between tools.

As far as the specific issue you raise of compliant URIs, it is usually possible to convert a non-compliant document into a compliant one.  If you use the SBOL Validator and provide a URI prefix and optionally a version, it will attempt to make a compliant document for you using this URI prefix.  It will even extract displayIds from the URIs to make this work.  This same feature is used by SynBioHub to make URIs both be in the repository namespace and make them compliant.  Therefore, compliance is not a hard requirement for any tools.  Please log an issue on the SBOL Designer issue tracker to enable conversion into compliant URIs.  We would like to have them in the tooling, but we can introduce them as needed to improve exchange.

Also, I would be happy to chat with you about this, if you would like to discuss more.

**Comment by chrismacklin** [comment]
I guess the frustrating part from my perspective as a tool author is that this higher tier of "compliant" isn't really made very evident in the right places.  I would naively assume that "compliant" means "adheres to the specification", not "adheres to a more restrictive subset of the specification".

Seems like this would be a good candidate for improving the text of the spec, to make this "compliant" notion a lot more visible and cross-referenced from the fields in the spec that are actually required for "compliance".

**Comment by cjmyers** [comment]
Agreed.  The descriptions of this could be improved.

I’m still holding out hope that we can make this required.  The people that have done serious tooling for SBOL 2 have come to really like compliant URIs, so it may be worth trying to make this required, so we would eliminate the multiple tiers.  The allure of complete flexibility though is very attractive to some, so we will see.

**Comment by chrismacklin** [comment]
When you say "compliant uris", do you specifically mean the formatting of the URIs themselves?  Or the presence/absence of all variants of them in identified?  (identity/persistentIdentity/displayId)

**Comment by cjmyers** [comment]
I mean rules sbol-10215 to sbol-10219.  A document that satisfies these rules is said to have compliant SBOL objects.

The term compliant URI is not a good one.  This is why the title of Section 12.3 is called Compliant SBOL Objects.  However, we often say compliant URIs because it relates to how the URI is formatted.  However, the ramifications of these rules result in other fields having requirements.  For example, when you say that the URI must end with the displayId and, if specified the version, then you must have a displayId.  When you say that a URI must be the persistentIdentity followed by the version, if specified, then there must be a persistentIdentity.  So, while the rules are on the formatting of the URIs, they imply other features about the SBOL object properties.

**Comment by chrismacklin** [comment]
Yet even those rules are internally inconsistent.  Rule sbol-10215 is in the "green star" category, which states that
"A star indicates a RECOMMENDED condition for following best practices. This rule is not strictly a matter of 11 SBOL conformance, but its recommendation comes from logical reasoning. If an SBOL document does not 12 follow this rule, it is still valid SBOL, but it might have degraded functionality in some tools."
yet the validator will not validate a document without displayId as valid SBOL.  A document without displayId is absolutely valid SBOL.

**Comment by cjmyers** [comment]
Yes, the validator will validate it.  There is a switch on the validator to allow non-compliant.  You can also turn off completeness checking, and you can turn on the other best practice rules.

**Comment by chrismacklin** [comment]
Ok, I think I see the whole picture now.

I will consider an SEP to improve the documentation of the distinction.  Since apparently "compliance" is important for actually generating documents that tools can read, this notion needs to be a lot more visible in the spec.

**Comment by cjmyers** [comment]
SEPs are only for changes in the data model.  You can simply log a tracker item for something like this.  Suggested changes would be appreciated too.

**Comment by jakebeal** [comment]
In fact, Chris, if you've got good suggestions for a clarification, just write them up and make a pull request.  The editors can then review for incorporation directly.

**Comment by cjmyers** [comment]
FYI: this actually came about due to a bug in libSBOLj that I’ve just fixed.  Missing displayIds should be okay, but due to this bug tooling that used libSBOLj ran into problems when they were missing.  This meant that ICE and SBOLDesigner could not opening files with missing displayIds.

**Comment by jakebeal** [comment]
Can this be closed as moot, now that displayId is required in SBOL 3?

**Comment by cjmyers** [comment]
Yes
