### ISSUE TITLE
2.1.0 Specification has contradicting examples of the PROVO-O namespace  

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/SBOL-specification#98]
At the bottom of page 63, the text leads me the reader to believe that the provenance namespace is:
"https://www.w3.org/TR/prov-o/"

However, the serialization example on p. 67 shows the namespace as:
"http://www.w3.org/ns/prov"

Which is correct?  Thanks!

**Comment by cjmyers** [comment]
Prov namespace should be:

http://www.w3.org/ns/prov# <http://www.w3.org/ns/prov#>

The page in the text is where you can find the description which includes the namespaces to use here:

https://www.w3.org/TR/2013/REC-prov-o-20130430/#namespaces <https://www.w3.org/TR/2013/REC-prov-o-20130430/#namespaces>

Chris

**Comment by chrisAta** [comment]
Not an issue, the only time 'https://www.w3.org/TR/prov-o/' is used is when first introducing PROV-O in the spec.
